#!/usr/bin/make -f
#
# Makefile for zlibdec 1.1.3 (for PlayStation 2)
#
# zlib data compression library version 1.1.3 (July 9th, 1998)
# Copyright (C) 1995-1998 Jean-loup Gailly and Mark Adler
#
.PHONY: all clean

all:
	@echo "placeholder"
clean:
	@echo "placeholder"
